[package]
name = "google-photos-takeout-util"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
eframe = "0.31.1"
little_exif = "0.6.4"
rfd = "0.15.3"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
zip = "2.6.1"
